baseurl = "/"
languageCode = "en-us"
title = "ARCHIMED user documentation"
theme = "learn"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
relativeurls = true

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
    editURL = "https://github.com/VEZY/archimed_website"
    author = "R. VEZY"
    description = "The user documentation for the ARCHIMED model"
    # Shows a checkmark for visited pages on the menu
    showVisitedLinks = true
    # Disable search function. It will hide search bar
    disableSearch = false
    # Javascript and CSS cache are automatically busted when new version of site is generated.
    # Set this to true to disable this behavior (some proxies don't handle well this optimization)
    disableAssetsBusting = false
    # Set this to true to disable copy-to-clipboard button for inline code.
    disableInlineCopyToClipBoard = false
    # A title for shortcuts in menu is set by default. Set this to true to disable it.
    disableShortcutsTitle = false
    # When using mulitlingual website, disable the switch language button.
    disableLanguageSwitchingButton = false
    # Hide breadcrumbs in the header and only show the current page title
    disableBreadcrumb = true
    # Hide Next and Previous page buttons normally displayed full height beside content
    disableNextPrev = false
    # Order sections in menu by "weight" or "title". Default to "weight"
    ordersectionsby = "weight"
    # Change default color scheme with a variant one. Can be "red", "blue", "green".
    themeVariant = "archimed"
    # Provide a list of custom css files to load relative from the `static/` folder in the site root.
    custom_css = ["css/foo.css", "css/bar.css"]

