---
chapter: false
date: "2020-06-09T12:15:33+02:00"
pre: <b>0.1. </b>
title: Download
weight: 21
---

# Data

To run an ARCHIMED-φ simulation, you'll need a working example. Please download it from here: 

{{%attachments pattern=\"example_inputs.zip\" /%}}

At the moment, don't worry about the organization of the folder nor the file contents. We'll get into this very soon in the [organization page](../../2-inputs/1-organisation/).

# ARCHIMED-φ executable

ARCHIMED-φ is programmed in Java. The main benefit is that a same `.jar` file can be executed in all platforms compatible with Java (*i.e.* Windows, Mac, Linux...). 
Please download the executable (e.g. `archimed-phys.jar`):

{{%attachments pattern=\"archimed-phys.jar\" /%}}


Then, place it at the root of the example directory, *i.e.* next to the `config.yml` file.

{{% notice note %}}
You can place `archimed-phys.jar` wherever you please, but it is good practice to place the executable in the folder of each simulation project for enhanced reproducibility.
{{% /notice %}}
