---
chapter: false
date: "2020-09-23T12:15:33+02:00"
pre: <b>1. </b>
title: Organisation
weight: 41
---

# Outputs organisation

Several output files are generated by an ARCHIMED-φ simulation. Depending on the options configured in the `config.yaml` input file (see [this section](../../3-inputs/2-general_config/)), you'll find: 

- inputs: several input files, eventually enriched by simulation results, such as the constants used as inputs (`const.yml`), the meteorology data (`meteo.csv`), the generated soil pavement (`pavement.gwa`), the scene file (`.ops` file) and the object files (e.g. `.opf` plant file). 

- results: simulation outputs at different scales, such as the simulated values for each component in the scene (`component_values.csv`), and the aggregation at object scale (`summary.csv`). 

- log: a session log for potential errors in the model (`session.log`). This file is useful for debugging the model.

It is recommended to follow along with the example files provided in the previous page opened in your preferred editor. We recommend [Atom](https://atom.io/) or [VS Code](https://code.visualstudio.com/). They are both open source and have packages to view and edit YAML (`.yml`), CSV (`.csv`) and XML files (`.ops`, `.opf` and `.gwa`).

Here is a tree view of the files we get by simulating the example simulation given in [this section](../../3-inputs/) with a little description for each:

```bash
📂
├── 📜coffee-1-step00002.opf   # -> The input plant file enriched by simulation results 
├── 📜coffee-step00002.ops     # -> The input 3D scene file
├── 📜component_values.csv     # -> The simulation results at component scale
├── 📜const.yml                # -> constants used in the model (inputs or default)
├── 📜meteo.csv                # -> the input meteorology file
├── 📜pavement-1-step00002.gwa # -> The input soil file in gwa format.
├── 📜scene_values.csv         # -> the meteorology file
├── 📜session.log              # -> the log file (used for debugging)
└── 📜summary.csv              # -> the summary at object scale
```

{{% notice note %}}
The names of the output files depends on the name they were given as inputs and on configuration options for the `.ops`, `.opf` and `.gwa` files.
{{% /notice %}}
