---
chapter: false
date: "2020-09-23T12:15:33+02:00"
pre: <b>3. </b>
title: Results
weight: 43
---

# Results files


## component values

The `component_values.csv` file contains the outputs of the simulation at component scale  (`e.g.` the light interception of each leaf) for each individual object (`e.g.` a plant). The variables written in this file are controlled by the `component_variables` parameter in [config.yml](../../3-inputs/2-general_config/)).

The table below summarizes the information about all possible variables. All values in $W \cdot m^{-2}$ are per component surface ($W \cdot m_{component}^{-2}$). All other values are integrated at the component scale, and possibly over the time-step (*e.g.* $J$ can be considered $J \cdot component^{-1} \cdot timestep^{-1}$, or $\mu mol$ can be considered $\mu mol\cdot component^{-1} \cdot timestep^{-1}$).

```{r echo=FALSE}
df = read.csv("3-results.files/component_variables.csv", sep = ";")
knitr::kable(df)
```

This table can be downloaded here:

{{%attachments pattern=\"component_variables.csv\" /%}}

Note that all `barycentre_*` variables are computed when required, so they slow down model execution time a little bit when set to `true`. 

## summary

The `summary.csv` file summarizes simulated values at plot scale for each Item in the scene (*e.g.* plant, soil) for each time-step, such as the total leaf area or intercepted shortwave radiation.

## scene values

The `scene_values.csv` file summarizes simulated values at plot scale for each time-step, such as the total leaf area or intercepted shortwave radiation.
