---
chapter: false
date: "2020-06-09T12:15:33+02:00"
pre: <b>1. </b>
title: Organisation
weight: 31
---

# Inputs organisation

Several input files are mandatory for an ARCHIMED-φ simulation: the general configuration file (`config.yml`), the meteorology data (`meteo.csv`), the models configuration (*e.g.* `plant_coffee.yml`), and the scene (e.g. `.ops` and `.opf` files). There is also an input file for the physical constants (`const.yml`) that is optional because ARCHIMED defines default values if not provided.

It is recommended to follow along with the example files provided in the previous page opened in your preferred editor. We recommend [Atom](https://atom.io/) or [VS Code](https://code.visualstudio.com/). They are both open source and have packages to view and edit YAML (`.yml`), CSV (`.csv`) and XML files (`.ops`, `.opf` and `.gwa`).

Here is a tree view of the files and folders with a little description for each:

```bash
📦
├── 📜config.yml               # -> Here is the general configuration file
├── 📜const.yml                # -> constants used in the model
├── 📜meteo.csv                # -> the meteorology file
├── 📂model                    # -> all the models configuration files are listed in this folder
│   └── 📜plant_coffee.yml     # An example config for a Coffea plant.
├── 📂scene                    # -> all the 3D scenes files are listed in this folder
│   ├── 📜coffee.ops           # An example scene with one coffee
│   └── 📂opf                  # The folder that list the available `.opf` files for the plant geometry
│       └── 📜coffee.opf       # An example coffee plant geometry and topology file)
└── 📜soil.yml                 # An example soil file
```

Many input files use the YAML format. It is a data serialization language designed to be directly writable and readable by humans. There are tons of resources on the web (*e.g.* [learnxinyminutes.com](https://learnxinyminutes.com/docs/yaml/), [Wikipedia](https://en.wikipedia.org/wiki/YAML), [this blog post](https://rollout.io/blog/yaml-tutorial-everything-you-need-get-started/)), but you should be fine just by seeing the files structure. 

{{% notice note %}}
The names of the input files are not mandatory, but it is best to keep a rather standard naming nevertheless. For example `soil.yml` can become `soil_1.yml` or `soil_montpellier.yml`, but it is still recommended to keep "soil" in the name.
{{% /notice %}}
