---
chapter: false
date: "2020-06-09T12:15:33+02:00"
pre: <b>3. </b>
title: Constant parameter file
weight: 33
bibliography: references.bib
---

# `const.yml`

This file lists all constants and their values used in ARCHIMED-φ. The file is optional. The example file provided below lists the default values used in ARCHIMED (their values are also provided in this page for information).

{{%attachments pattern=\"const.yml\" /%}}

{{% notice info %}}
You can safely ignore this page for the vast majority of use cases. You don't need to know or understand everything in this page, it is only provided for convenience in case the user has specific needs.
{{% /notice %}}


- `co2_to_heat_boundary_layer_conductance` is used to convert the boundary layer conductance to heat into the boundary layer conductance to $CO_2$ with the following equation. The default value is 1.32 as given in the [MAESPA model](https://bitbucket.org/remkoduursma/maespa/src/0cb01e8149f64bd2122831a41d73f97f4e08a34d/maestcom.f90#lines-56), or in the [bigleaf R package](https://rdrr.io/cran/bigleaf/man/Gb.Thom.html) following @hicks1987preliminary:

$$Gb_{CO_2}=\frac{Gb_{heat}}{co2\_to\_heat\_boundary\_layer\_conductance}$$

- `heat_to_water_boundary_layer_conductance` is used to convert boundary layer conductance to heat into boundary layer conductance to water (default to 1.075): 

$$Gb_{H_2O}= Gb_{heat} \cdot heat\_to\_water\_boundary\_layer\_conductance$$

- `co2_to_water_conductance` is used to convert a stomatal conductance to $CO_2$ into a stomatal conductance for $H_2O$ (default to 1.57):

$$Gb_{H_2O}= Gb_{CO_2} \cdot co2\_to\_water\_conductance$$

- `forced_heat_BL_conductance_proportionality_factor` is used compute the boundary layer conductance for heat under forced convection (default to 1000/3):

$$Gbh_{forced} = \frac{\sqrt{\frac{wind}{specificLength}}}{C}$$

See @leuningLeafNitrogenPhotosynthesis1995 for more details (equation E1 from Appendix E).

- `atmospheric_CO2_concentration` defines the default $CO_2$ concentration in the atmosphere in ppm. It is used only if the $CO_2$ variable is missing from the [meteorology file](../6-meteo/index.html) (default to 400 ppm).  

- `atmospheric_O2_concentration` defines the $O_2$ concentration in the atmosphere in ppm. Default to 210.0 ppm. It is used to compute the rubisco-limited carboxylation rate $W_c$ ($\mu mol_{CO_2} \cdot m^{-2} \cdot s^{-1}$):

$$W_c = \frac{(Vc_{max} \cdot C_i)}{C_i + K_c \cdot (1.0 + \frac{atmospheric\_O2\_concentration}{K_o})}$$
See @farquharBiochemicalModelPhotosynthetic1980 for more details (equation 9).

- `water_vapour_to_dry_air_molecular_weight_ratio` is used to convert molecular weight of water vapour into dry air. Default to 0.622. It is used to compute the [psychrometric constant](https://en.wikipedia.org/wiki/Psychrometric_constant) ($\gamma$, in $kPa \cdot °C^{-1}$) from atmospheric pressure (kPa):

$$\gamma = \frac{Cp_{air} \cdot P}{water\_vapour\_to\_dry\_air\_molecular\_weight\_ratio \cdot lambda}$$


- `air_specific_heat_constant_pressure` is the [specific heat](https://en.wikipedia.org/wiki/Specific_heat_capacity) of air at constant pressure in $J \cdot K^{-1} \cdot kg^{-1}$. Default to 1013. It is used to compute the [psychrometric constant](https://en.wikipedia.org/wiki/Psychrometric_constant) (see equation above).

- `gravitational_acceleration` is the gravitational acceleration in $m \cdot s^{-2}$ and is used to compute the pressure from the elevation. Default to 9.81. See @stull2012introduction and the [BigLeaf](https://bitbucket.org/juergenknauer/bigleaf/src/master/) R package for more details.


- `celsius_to_kelvin` is used to convert Celsius degrees into Kelvin degrees. Default to 273.15. 

- `universal_gas_constant` defines the [universal gas constant](https://en.wikipedia.org/wiki/Gas_constant) in $J \cdot mol^{-1} \cdot K^{-1}$. Default to 8.314. It is used to compute the temperature dependence for the assimilation parameters and to convert conductance in $mol \cdot m^{-2} \cdot s^{-1}$ into $m \cdot s^{-1}$.

- `dry_air_gaz_constant` is the gaz constant of dry air (Rd) in $J \cdot kg^{-1} \cdot K^{-1}$. Default to 287.0586. It is used to compute the air density following @foken2008micrometeorology: 

$$R_{specific} = \frac{P}{Rd \cdot T_{air}}$$

See [here](https://en.wikipedia.org/wiki/Gas_constant) for more details (Specific gas constant section).

- `ref_atmospheric_pressure_sea_level` is the reference atmospheric pressure at sea level. It defaults to 101.325 kPa.

- `Stefan_Boltzmann_sigma` is the [Stefan-Boltzmann constant](https://en.wikipedia.org/wiki/Stefan%E2%80%93Boltzmann_law) (noted $\sigma$). Its default value is at 5.67477e-08 $W \cdot m^{-2} \cdot K^{-4}$. It is used to compute the emission of thermal infrared radiation (Re_TIR) by a black body: 

$$Re_{TIR} =  \sigma \cdot T^4$$
- `sun_irradiance_to_photons` is used to convert sunlight irradiance $W \cdot m^{-2}$ into PPFD ($\mu mol \cdot m^{-2} \cdot s^{-1}$). It defaults to 4.57 $\frac{\mu mol \cdot m^{-2} \cdot s^{-1}}{W \cdot m^{-2}}$

## References