---
chapter: false
date: "2020-06-09T12:15:33+02:00"
pre: <b>4.3. </b>
title: Geometry file
weight: 37
---

# `.gwa`

The `.gwa` files are used to represent any geometrical object. It is based on the same format than the `.opf` (and is an `XML` too), but without the topology. 

A simple example of a virtual table is available here:

{{%attachments pattern=\"table.gwa\" /%}}

And here is a 3d render of this file: 

<div class="sketchfab-embed-wrapper">
<iframe title="A 3D model" width="640" height="480" src="https://sketchfab.com/models/f15c79006b2f4f5cb831c21ce37d7da4/embed?autostart=1&amp;ui_controls=1&amp;ui_infos=1&amp;ui_inspector=1&amp;ui_stop=1&amp;ui_watermark=1&amp;ui_watermark_link=1" frameborder="0" allow="autoplay; fullscreen; vr" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
<p style="font-size: 13px; font-weight: normal; margin: 5px; color: #4A4A4A;">
<a href="https://sketchfab.com/3d-models/a-simple-table-f15c79006b2f4f5cb831c21ce37d7da4?utm_medium=embed&utm_source=website&utm_campaign=share-popup" target="_blank" style="font-weight: bold; color: #1CAAD9;">A simple table</a>
by <a href="https://sketchfab.com/rvezy?utm_medium=embed&utm_source=website&utm_campaign=share-popup" target="_blank" style="font-weight: bold; color: #1CAAD9;">rvezy</a>
on <a href="https://sketchfab.com?utm_medium=embed&utm_source=website&utm_campaign=share-popup" target="_blank" style="font-weight: bold; color: #1CAAD9;">Sketchfab</a>
</p>
</div>

If you open the file, you'll see several sextions. First, there is the header:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<gwa version="1.0">
```

The first line defines the `xml` format, and the second one defines the `gwa` format.

Then comes the attributes: 

```xml
<attributes>
	<attribute name="Color" class="Color"/>
</attributes>
```

It is the same as for the `attributeBDD` from the [`opf` format](../2-opf/index.html#attributeBDD) (go there for more details).

Then the meshes are defined one after another with their respective data: points, normals, face: 

```xml
<mesh id="2" label="Cylinder">
	<points>
		-245.0	-500.0	0.0	-245.0	-500.0	60.0	-245.0	-500.0	120.0	-245.0	-500.0	180.0	-245.0	-500.0	240.0	-245.0	-500.0	300.0	-250.0	-495.0	0.0	-250.0	-495.0	60.0	-250.0	-495.0	120.0	-250.0	-495.0	180.0	-250.0	-495.0	240.0	-250.0	-495.0	300.0	-255.0	-500.0	0.0	-255.0	-500.0	60.0	-255.0	-500.0	120.0	-255.0	-500.0	180.0	-255.0	-500.0	240.0	-255.0	-500.0	300.0	-250.0	-505.0	0.0	-250.0	-505.0	60.0	-250.0	-505.0	120.0	-250.0	-505.0	180.0	-250.0	-505.0	240.0	-250.0	-505.0	300.0
	</points>
	<normals>
		-1.0	-2.683151E-7	0.0	-1.0	0.0	0.0	-1.0	0.0	0.0	-1.0	0.0	0.0	-1.0	0.0	0.0	-1.0	2.683151E-7	0.0	2.7502296E-7	-1.0	0.0	-2.3477572E-8	-1.0	0.0	-2.3477572E-8	-1.0	0.0	-2.3477572E-8	-1.0	0.0	-2.3477572E-8	-1.0	0.0	-2.683151E-7	-1.0	0.0	1.0	2.7502296E-7	0.0	1.0	-2.3477572E-8	0.0	1.0	-2.3477572E-8	0.0	1.0	-2.3477572E-8	0.0	1.0	-2.3477572E-8	0.0	1.0	-2.683151E-7	0.0	-2.7502296E-7	1.0	0.0	2.3477572E-8	1.0	0.0	2.3477572E-8	1.0	0.0	2.3477572E-8	1.0	0.0	2.3477572E-8	1.0	0.0	2.683151E-7	1.0	0.0
	</normals>
	<faces>
		<face Id="0">
			0	6	7
		</face>
		<face Id="1">
			7	1	0
		</face>
	  [...]
	</faces>		
	<Color>Color 0 0 255</Color>
</mesh>
```

where `[...]` denotes data that is not displayed here for clarity.

The format of the meshes follows the one from the [meshBDD](../2-opf/index.html#meshBDD) in the `opf` format, see this documentation for more details.

More information about the `.gwa` files are available from [the AMAPStudio documentation](http://amapstudio.cirad.fr/soft/xplo/private/the_gwa_format_-_geometry_with_attributes)).
